### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by PatrickAlphaC** [Usman75/Lazy-trader-bot#2]
Hi @Usman75,

Thank you for your submission. Is there a video here?

**Comment by Usman75** [comment]
Hi @PatrickAlphaC  ,
first sorry I am not added video demo at the time of submission due to having some internet issue. here I updated the Demo video. kindly check it out. https://youtu.be/coTeSF2PjAU

**Comment by PatrickAlphaC** [comment]
Got it, thank you!
